### ISSUE TITLE
詢問翻譯貢獻流程

### ISSUE THREAD

**Issue by youchenlee** [toomore/publiccodenet.standard#2]
Hi 想了解翻譯貢獻的流程，比如：

1. 參與者使用 https://weblate.steps.tw/projects/standard-for-public-code/ 進行翻譯後，push 翻譯結果回此 repo 的方式為何？
2. 如何 review？
3. 如何檢視結果？

謝謝

**Comment by moda-l10n** [comment]
本次翻譯專案已結束且Weblate伺服器已停止維運，相關貢獻可直接於GitHub提報，如經審核同意接受拉取要求（PullRequest），將可直接於GitHub上檢視結果。
